### ISSUE TITLE
How to run on multiple machines?

### ISSUE THREAD

**Issue by hjk41** [qnib/docker-slurmd#1]
Is it possible to run this on multiple machines (instead of multiple dockers in the same machine)? Could you share some details on how to do this?

**Comment by ChristianKniep** [comment]
Hey @hjk41,

I presented it here: http://doc.qnib.org/2014-11-05_HPCAC_KniepChristian_DockerMPI.pdf
In essence I expose the port 22 to the physical host and only run one at a time.
Unfortunately I am on vacation shortly so I am not able to producce some more infos, please check out the other papers: http://doc.qnib.org/

If you have more question just fire at will. I am back next week.

Cheers
Christian

**Comment by hjk41** [comment]
Hi Christian,

Thanks for the quick reply. So you used --net=host? I guess you must have
either changed the SSH port number of either the host or the docker image?

Thanks,
chuntao

On Tue, Sep 15, 2015 at 3:47 AM, Christian Kniep notifications@github.com
wrote:

> Hey @hjk41 https://github.com/hjk41,
> 
> I presented it here:
> http://doc.qnib.org/2014-11-05_HPCAC_KniepChristian_DockerMPI.pdf
> In essence I expose the port 22 to the physical host and only run one at a
> time.
> Unfortunately I am on vacation shortly so I am not able to producce some
> more infos, please check out the other papers: http://doc.qnib.org/
> 
> If you have more question just fire at will. I am back next week.
> 
> Cheers
> Christian
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qnib/docker-slurmd/issues/1#issuecomment-140187412.

## 

HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by ChristianKniep** [comment]
Thinking about it, I was using `pipework` from Jerome. I started the containers with `--net none` and used the tool that hooks into the docker socket and listens for events. If a container was spun up I was attaching a dedicated IP next to the hosts IP.

Gotta run, hope that helps so far...

**Comment by hjk41** [comment]
Thanks for the information. I will have a try.

On Tue, Sep 15, 2015 at 5:31 PM, Christian Kniep notifications@github.com
wrote:

> Thinking about it, I was using pipework from Jerome. I started the
> containers with --net none and used the tool that hooks into the docker
> socket and listens for events. If a container was spun up I was attaching a
> dedicated IP next to the hosts IP.
> 
> Gotta run, hope that helps so far...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qnib/docker-slurmd/issues/1#issuecomment-140336640.

## 

HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by ChristianKniep** [comment]
Have you sorted it out? If so, please close the issue. Otherwise I am back, so feel free to shoot. :)
